//! Bike health report: a one-click, self-contained HTML snapshot of the
//! ECU's state — identity, fault codes with plain-language guidance, and a
//! live-data snapshot. The use case straight from owner forums: pre-purchase
//! inspections of used bikes, and "email your mechanic what the ECU says".

use motodiag_ecu_defs::schema::ChannelSpec;
use motodiag_ecu_defs::EcuDefinition;

use crate::dtc::Dtc;
use crate::live_data::Reading;
use crate::session::EcuIdentity;

/// One channel's reference range as already resolved by the frontend
/// (`specResolution.ts`) — stock, community-adjusted, or the owner's own
/// target. The report renders this; it never re-resolves it, so the
/// precedence logic can't fork between the two.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct BikeReportSpec {
    pub key: String,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub target: Option<f64>,
    pub condition: String,
    /// "stock" | "community-adjusted" | "user-override".
    pub source: String,
    pub label: String,
}

/// The saved bike profile driving this report, passed in from the frontend
/// garage — the health report is rendered Rust-side but has no persistence
/// or resolution logic of its own.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct BikeReportSection {
    pub profile_name: String,
    pub brand: String,
    pub model: String,
    pub year: Option<u16>,
    /// Pre-rendered one-line mod summary (see `describeMods` in garage.ts).
    pub mods_summary: String,
    pub specs: Vec<BikeReportSpec>,
}

pub struct ReportInput<'a> {
    pub def: &'a EcuDefinition,
    pub identity: &'a EcuIdentity,
    pub dtcs: &'a [Dtc],
    pub readings: &'a [Reading],
    /// Whether this session ran against the built-in simulator (stamped
    /// prominently so a simulated report can never pass as a real one).
    pub simulated: bool,
    /// Milliseconds since the Unix epoch, formatted client-side.
    pub generated_at_ms: u64,
    /// Present only when the connection was made from a saved garage
    /// profile — `None` renders a byte-identical legacy report.
    pub bike: Option<&'a BikeReportSection>,
}

fn range_text(spec: &ChannelSpec) -> String {
    match (spec.min, spec.max) {
        (Some(min), Some(max)) => format!("{min:.2}–{max:.2}"),
        (Some(min), None) => format!("≥ {min:.2}"),
        (None, Some(max)) => format!("≤ {max:.2}"),
        (None, None) => spec
            .target
            .map(|t| format!("target {t:.2}"))
            .unwrap_or_else(|| spec.condition.clone()),
    }
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Render the report as a single self-contained HTML document (inline CSS,
/// no external resources — it must open cleanly from a file:// attachment).
pub fn render_html(input: &ReportInput) -> String {
    let mut html = String::with_capacity(16 * 1024);
    let def = input.def;

    html.push_str(&format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>MotoDiag health report — {name}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 2rem auto; max-width: 780px; padding: 0 1rem; color: #1a1c20; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 0.2rem; }}
  h2 {{ font-size: 1.1rem; margin-top: 1.8rem; border-bottom: 2px solid #e0342b; padding-bottom: 0.3rem; }}
  .meta {{ color: #667; font-size: 0.9rem; }}
  .banner {{ background: #fff3cd; border: 1px solid #d4a017; border-radius: 8px; padding: 0.6rem 1rem; margin: 1rem 0; font-size: 0.95rem; }}
  .banner.sim {{ background: #ffe3e0; border-color: #e0342b; font-weight: 600; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 0.6rem; }}
  th, td {{ text-align: left; padding: 0.45rem 0.7rem; border-bottom: 1px solid #ddd; font-size: 0.95rem; }}
  th {{ color: #667; font-weight: 600; font-size: 0.85rem; }}
  .code {{ font-family: ui-monospace, Menlo, Consolas, monospace; }}
  .ok {{ color: #1d7a44; font-weight: 600; }}
  .bad {{ color: #c0271c; font-weight: 600; }}
  .dtc {{ border: 1px solid #ddd; border-radius: 8px; padding: 0.7rem 1rem; margin: 0.7rem 0; }}
  .dtc-title {{ font-weight: 700; }}
  .dtc h4 {{ margin: 0.6rem 0 0.2rem; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px; color: #667; }}
  .dtc ol {{ margin: 0.2rem 0 0; padding-left: 1.4rem; font-size: 0.92rem; }}
  footer {{ margin-top: 2.5rem; color: #99a; font-size: 0.8rem; border-top: 1px solid #eee; padding-top: 0.8rem; }}
</style>
</head>
<body>
<h1>Bike health report</h1>
<div class="meta">{manufacturer} — {name}{models}</div>
<div class="meta">Generated by MotoDiag · <span class="code" data-ts="{ts}">{ts}</span> (Unix ms)</div>
"#,
        name = esc(&def.ecu.name),
        manufacturer = esc(&def.ecu.manufacturer),
        models = if def.ecu.models.is_empty() {
            String::new()
        } else {
            format!(" · {}", esc(&def.ecu.models.join(", ")))
        },
        ts = input.generated_at_ms,
    ));

    if input.simulated {
        html.push_str(
            r#"<div class="banner sim">SIMULATED SESSION — this report was generated against
MotoDiag's built-in ECU simulator, not a real motorcycle.</div>"#,
        );
    }
    if !def.ecu.verified {
        html.push_str(
            r#"<div class="banner">Unverified ECU definition: decoded values below come from a
definition file not yet confirmed against a real ECU of this type. Treat readings as
indicative, not authoritative.</div>"#,
        );
    }

    html.push_str(&format!(
        "<h2>ECU identification</h2>\n<p class=\"code\">{}</p>\n",
        esc(&input.identity.text)
    ));

    let mut spec_by_key: std::collections::HashMap<&str, &BikeReportSpec> =
        std::collections::HashMap::new();
    if let Some(bike) = input.bike {
        html.push_str("<h2>Bike</h2>\n");
        html.push_str(&format!(
            "<p><strong>{}</strong> — {} {}{}</p>\n<p class=\"meta\">Modifications: {}</p>\n",
            esc(&bike.profile_name),
            esc(&bike.brand),
            esc(&bike.model),
            bike.year.map(|y| format!(" ({y})")).unwrap_or_default(),
            esc(&bike.mods_summary),
        ));
        for spec in &bike.specs {
            spec_by_key.insert(spec.key.as_str(), spec);
        }
        if bike.specs.iter().any(|s| s.source != "stock") {
            html.push_str(
                r#"<div class="banner">Some reference ranges in this report are community-adjusted for this bike's modifications or set by the owner — they are not manufacturer specifications. Look at the Source column in the live-data table below.</div>"#,
            );
        }
    }

    html.push_str("<h2>Fault codes</h2>\n");
    if input.dtcs.is_empty() {
        html.push_str("<p class=\"ok\">No stored fault codes.</p>\n");
    } else {
        html.push_str(&format!(
            "<p class=\"bad\">{} stored fault code(s):</p>\n",
            input.dtcs.len()
        ));
        for dtc in input.dtcs {
            html.push_str(&format!(
                "<div class=\"dtc\"><div class=\"dtc-title\"><span class=\"code\">{:04X}</span> — {} <span class=\"meta code\">(status 0x{:02X})</span></div>\n",
                dtc.code,
                esc(dtc.description.as_deref().unwrap_or("unknown code")),
                dtc.status,
            ));
            if !dtc.causes.is_empty() {
                html.push_str("<h4>Likely causes</h4><ol>");
                for cause in &dtc.causes {
                    html.push_str(&format!("<li>{}</li>", esc(cause)));
                }
                html.push_str("</ol>");
            }
            if !dtc.checks.is_empty() {
                html.push_str("<h4>What to check</h4><ol>");
                for check in &dtc.checks {
                    html.push_str(&format!("<li>{}</li>", esc(check)));
                }
                html.push_str("</ol>");
            }
            html.push_str("</div>\n");
        }
    }

    html.push_str("<h2>Live data snapshot</h2>\n");
    if input.readings.is_empty() {
        html.push_str("<p class=\"meta\">No live data captured.</p>\n");
    } else {
        let has_specs = !spec_by_key.is_empty();
        html.push_str("<table><tr><th>Channel</th><th>Value</th><th>Unit</th>");
        if has_specs {
            html.push_str("<th>Reference range</th><th>Source</th>");
        }
        html.push_str("</tr>\n");
        for r in input.readings {
            html.push_str(&format!(
                "<tr><td>{}</td><td class=\"code\">{:.2}</td><td>{}</td>",
                esc(&r.name),
                r.value,
                esc(&r.unit),
            ));
            if has_specs {
                if let Some(spec) = spec_by_key.get(r.key.as_str()) {
                    let channel_spec = ChannelSpec {
                        min: spec.min,
                        max: spec.max,
                        target: spec.target,
                        condition: spec.condition.clone(),
                    };
                    let range_text = range_text(&channel_spec);
                    let cell_class = match channel_spec.in_range(r.value) {
                        Some(true) => "ok",
                        Some(false) => "bad",
                        None => "meta",
                    };
                    html.push_str(&format!(
                        "<td class=\"{cell_class}\">{}</td><td class=\"meta\">{}</td>",
                        esc(&range_text),
                        esc(&spec.label),
                    ));
                } else {
                    html.push_str("<td class=\"meta\">—</td><td class=\"meta\">—</td>");
                }
            }
            html.push_str("</tr>\n");
        }
        html.push_str("</table>\n");
    }

    html.push_str(
        "<footer>Produced by MotoDiag, an open-source diagnostics tool for MV Agusta &amp; \
         Ducati motorcycles. Readings reflect the moment of capture only.</footer>\n</body>\n</html>\n",
    );
    html
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::live_data::now_ms;

    fn sample_input(def: &EcuDefinition) -> (EcuIdentity, Vec<Dtc>, Vec<Reading>) {
        let identity = EcuIdentity {
            raw: b"IAW 5SM SIM v0.1".to_vec(),
            text: "IAW 5SM SIM v0.1".into(),
        };
        let dtcs = vec![Dtc {
            code: 0x0115,
            status: 0x60,
            description: Some("Throttle position sensor <fault>".into()),
            causes: vec!["TPS connector corrosion".into()],
            checks: vec!["Inspect & clean the connector".into()],
        }];
        let readings = vec![Reading {
            key: "rpm".into(),
            name: "Engine speed".into(),
            unit: "rpm".into(),
            value: 1250.0,
            timestamp_ms: now_ms(),
        }];
        let _ = def;
        (identity, dtcs, readings)
    }

    fn load_brutale_def() -> EcuDefinition {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../definitions");
        motodiag_ecu_defs::Registry::load_dir(&dir)
            .unwrap()
            .get("mv-5sm-brutale-910")
            .unwrap()
            .clone()
    }

    #[test]
    fn renders_all_sections_and_escapes_html() {
        let def = load_brutale_def();
        let (identity, dtcs, readings) = sample_input(&def);
        let html = render_html(&ReportInput {
            def: &def,
            identity: &identity,
            dtcs: &dtcs,
            readings: &readings,
            simulated: true,
            generated_at_ms: 1_752_130_800_000,
            bike: None,
        });

        assert!(html.contains("Bike health report"));
        assert!(html.contains("IAW 5SM SIM v0.1"));
        assert!(html.contains("0115"));
        assert!(html.contains("TPS connector corrosion"));
        assert!(html.contains("Engine speed"));
        assert!(html.contains("SIMULATED SESSION"));
        assert!(html.contains("Unverified ECU definition"));
        // The <fault> in the description must be escaped, not injected.
        assert!(html.contains("&lt;fault&gt;"));
        assert!(!html.contains("<fault>"));
        // No bike profile: no Bike section, no community/owner banner.
        assert!(!html.contains("<h2>Bike</h2>"));
        assert!(!html.contains("community-adjusted for this bike"));
    }

    #[test]
    fn clean_bike_reads_as_healthy() {
        let def = load_brutale_def();
        let (identity, _dtcs, readings) = sample_input(&def);
        let html = render_html(&ReportInput {
            def: &def,
            identity: &identity,
            dtcs: &[],
            readings: &readings,
            simulated: false,
            generated_at_ms: 0,
            bike: None,
        });
        assert!(html.contains("No stored fault codes"));
        assert!(!html.contains("SIMULATED SESSION"));
    }

    #[test]
    fn bike_profile_renders_section_sources_and_escapes_name() {
        let def = load_brutale_def();
        let (identity, dtcs, readings) = sample_input(&def);
        let bike = BikeReportSection {
            profile_name: "<script>alert(1)</script>".into(),
            brand: "MV Agusta".into(),
            model: "Brutale 910".into(),
            year: Some(2006),
            mods_summary: "open slip-ons (titanium) · dedicated EPROM".into(),
            specs: vec![BikeReportSpec {
                key: "rpm".into(),
                min: Some(1150.0),
                max: Some(1450.0),
                target: None,
                condition: "warm idle, open exhaust — community reference, unverified".into(),
                source: "community-adjusted".into(),
                label: "community reference — unverified".into(),
            }],
        };
        let html = render_html(&ReportInput {
            def: &def,
            identity: &identity,
            dtcs: &dtcs,
            readings: &readings,
            simulated: false,
            generated_at_ms: 0,
            bike: Some(&bike),
        });

        assert!(html.contains("<h2>Bike</h2>"));
        assert!(html.contains("MV Agusta"));
        assert!(html.contains("Brutale 910"));
        assert!(html.contains("open slip-ons (titanium)"));
        assert!(html.contains("community-adjusted for this bike"));
        assert!(html.contains("1150.00–1450.00"));
        assert!(html.contains("community reference"));
        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(html.contains("&lt;script&gt;"));
    }

    #[test]
    fn all_stock_sources_show_no_banner() {
        let def = load_brutale_def();
        let (identity, dtcs, readings) = sample_input(&def);
        let bike = BikeReportSection {
            profile_name: "Stock bike".into(),
            brand: "MV Agusta".into(),
            model: "Brutale 910".into(),
            year: None,
            mods_summary: "stock".into(),
            specs: vec![BikeReportSpec {
                key: "rpm".into(),
                min: Some(1100.0),
                max: Some(1300.0),
                target: None,
                condition: "warm idle, neutral".into(),
                source: "stock".into(),
                label: "stock reference".into(),
            }],
        };
        let html = render_html(&ReportInput {
            def: &def,
            identity: &identity,
            dtcs: &dtcs,
            readings: &readings,
            simulated: false,
            generated_at_ms: 0,
            bike: Some(&bike),
        });
        assert!(html.contains("<h2>Bike</h2>"));
        assert!(!html.contains("community-adjusted for this bike"));
    }
}
